pipeline {
  agent any
  environment {
    DOCKER_REG = "YOUR_DOCKER_REGISTRY/your-repo"
    APP_NAME = "netflix-service"
    MAVEN_SETTINGS = 'nexus-settings' // Jenkins credential id for settings.xml
    SONAR_TOKEN = credentials('sonar-token')
    NEXUS_USER = credentials('nexus-user')
    NEXUS_PASS = credentials('nexus-pass')
}


stages {
  stage('Checkout') {
    steps { checkout scm }
}


stage('Build') {
  steps {
    withCredentials([file(credentialsId: MAVEN_SETTINGS, variable: 'MAVEN_SETTINGS_XML')]) {
       sh "mvn -s $MAVEN_SETTINGS_XML clean package -DskipTests"
    }
  }
}


stage('Unit & Test') {
  steps { sh 'mvn test' }
}


stage('SonarQube Analysis') {
  steps {
    withEnv(["SONAR_TOKEN=${SONAR_TOKEN}"]) {
      sh "mvn sonar:sonar -Dsonar.login=${SONAR_TOKEN}"
    }
  }  
}


stage('Build Docker & Push') {
  steps {
    sh "docker build -t ${DOCKER_REG}:${env.BUILD_NUMBER} app/"
    sh "docker push ${DOCKER_REG}:${env.BUILD_NUMBER}"
  }
}


stage('Deploy to K8s') {
  steps {
    sh "kubectl apply -f k8s/deployment.yaml"
    sh "kubectl apply -f k8s/service.yaml"
  }
 }
}


post {
 always { echo "Pipeline finished" }
 }
}
